#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from _common import read_json, read_artifact_csv, sha256_file, SKILL_VERSION


def fmt(x, digits=4):
    if x is None or pd.isna(x):
        return "NA"
    try:
        return f"{float(x):.{digits}g}"
    except Exception:
        return str(x)


def _truthy(v):
    if isinstance(v, bool):
        return v
    return str(v).strip().lower() in {"true", "1", "yes"}


def result_sentence(r, default_level):
    ci = ""
    ci_level = float(r.get("ci_level")) if pd.notna(r.get("ci_level")) else default_level
    if pd.notna(r.get("ci_low")) and pd.notna(r.get("ci_high")):
        ci = f", {int(round(ci_level*100))}% CI [{fmt(r.get('ci_low'))}, {fmt(r.get('ci_high'))}]"
    effect = ""
    if pd.notna(r.get("effect_size")) and str(r.get("type")) != "welch_contrast":
        effect = f"; {r.get('effect_size_name', 'effect size')} = {fmt(r.get('effect_size'))}"
    p = f"; raw p = {fmt(r.get('p_value'))}"
    if str(r.get("p_adjust_method", "none")) != "none":
        p += f", adjusted p = {fmt(r.get('p_adjusted'))} ({r.get('p_adjust_method')})"
    nbits = []
    for c in ["n", "n_a", "n_b", "n_pairs"]:
        if c in r and pd.notna(r.get(c)):
            nbits.append(f"{c}={int(float(r.get(c)))}")
    ntext = f" ({', '.join(nbits)})" if nbits else ""
    return (
        f"**{r['analysis_item_id']}** [{r.get('analysis_role') or 'unspecified role'}; {r['type']}]{ntext}: "
        f"{r.get('estimate_name', 'estimate')} = {fmt(r.get('estimate'))}{ci}{effect}{p}."
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--plan", required=True)
    ap.add_argument("--cleaning-report", required=True)
    ap.add_argument("--cleaning-log")
    ap.add_argument("--results", required=True)
    ap.add_argument("--sensitivity-results")
    ap.add_argument("--preflight")
    ap.add_argument("--provenance")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    plan = read_json(args.plan)
    cleaning = read_json(args.cleaning_report)
    cleaning_log = pd.read_csv(args.cleaning_log) if args.cleaning_log else pd.DataFrame()
    results = read_artifact_csv(args.results)
    sensitivity = read_artifact_csv(args.sensitivity_results) if args.sensitivity_results else pd.DataFrame()
    preflight = read_json(args.preflight) if args.preflight else None
    provenance = read_json(args.provenance) if args.provenance else None
    level = float(plan.get("confidence_level", 0.95))

    lines = [
        f"# Analysis report — {plan.get('analysis_id')}",
        "",
        f"Generated by `scientific-data-analysis` v{SKILL_VERSION}. This report is a deterministic summary of declared analysis artifacts; scientific interpretation remains a researcher judgment.",
        "",
        "## 1. Research question and analysis contract",
        "",
        f"- Research question: {plan.get('research_question')}",
        f"- Profile: `{plan.get('profile')}`",
        f"- Unit of analysis: {plan.get('unit_of_analysis')}",
        f"- Confidence level for ordinary interval estimates: {int(round(level*100))}%",
        f"- Missing-data strategy: `{plan.get('missing_data', {}).get('strategy')}`",
        f"- Bootstrap/resampling method: `{plan.get('resampling', {}).get('method', 'percentile')}`; resamples: {plan.get('resampling', {}).get('n_resamples')}",
        f"- Plan version: `{plan.get('plan_version')}`",
        f"- Analysis-plan schema: `{plan.get('analysis_plan_schema_version', 'unspecified')}`",
        f"- Plan SHA-256: `{sha256_file(args.plan)}`",
        "",
        "## 2. Data and cleaning",
        "",
        f"- Raw rows: {cleaning.get('rows_initial')}",
        f"- Analysis-ready rows: {cleaning.get('rows_final')}",
        f"- Logged row-drop events: {cleaning.get('rows_dropped_events')}",
        f"- Raw input SHA-256: `{cleaning.get('input_sha256')}`",
        f"- Analysis-ready data SHA-256: `{cleaning.get('output_sha256')}`",
        f"- Independent-unit ID column: `{cleaning.get('id_column')}`",
        f"- Duplicate-ID policy: `{cleaning.get('id_duplicate_policy')}`; duplicate rows remaining: {cleaning.get('id_duplicate_rows_after_cleaning')}",
    ]
    agg = cleaning.get("technical_replicate_aggregation")
    if agg:
        lines.append(
            f"- Technical replicates: `{agg.get('method')}` aggregation over `{agg.get('group_by')}`; "
            f"{agg.get('rows_collapsed')} rows collapsed across {agg.get('groups_aggregated')} groups. "
            f"Original raw-row membership is preserved in `{agg.get('source_row_traceability_column', '_source_row_ids')}`."
        )
    else:
        lines.append("- Technical replicate aggregation: not applied.")
    if len(cleaning_log):
        if "rule_id" in cleaning_log.columns:
            counts = cleaning_log["rule_id"].astype(str).value_counts()
            lines.append("- Cleaning-event reasons: " + "; ".join(f"`{k}`={int(v)}" for k, v in counts.items()) + ".")
    elif args.cleaning_log:
        lines.append("- Cleaning-event reasons: none (empty cleaning log).")
    else:
        lines.append("- Cleaning log was not supplied to the report builder; reason-level summary omitted.")

    lines += ["", "## 3. Prespecified inferential results", ""]
    for _, r in results.iterrows():
        lines.append(result_sentence(r, level))
        if pd.notna(r.get("n_candidate_units")):
            lines.append(
                f"  - Missingness accounting ({r.get('missingness_unit', 'units')}): candidate={int(float(r.get('n_candidate_units')))}, "
                f"analyzed={int(float(r.get('n_analyzed_units')))}, excluded for missing/invalid analysis variables={int(float(r.get('n_missing_or_invalid_excluded')))}; "
                f"strategy=`{r.get('missing_data_strategy')}`."
            )
        if pd.notna(r.get("n_rows_missing_pair_id")) and int(float(r.get("n_rows_missing_pair_id"))) > 0:
            lines.append(
                f"  - Pair-ID validity: {int(float(r.get('n_rows_missing_pair_id')))} row(s) had missing pair IDs and were excluded before constructing paired analysis units."
            )
        if str(r.get("type")) in {"equivalence_tost_independent", "equivalence_tost_paired"}:
            verdict = "equivalence criterion met" if _truthy(r.get("equivalence_conclusion")) else "equivalence criterion not met"
            lines.append(
                f"  - TOST margins: [{fmt(r.get('equivalence_margin_lower'))}, {fmt(r.get('equivalence_margin_upper'))}] at alpha={fmt(r.get('equivalence_alpha'))}; "
                f"p_lower={fmt(r.get('tost_p_lower'))}, p_upper={fmt(r.get('tost_p_upper'))}; **{verdict}**."
            )
        if str(r.get("type")) in {"linear_regression", "ancova_two_group", "logistic_regression", "poisson_regression"}:
            diagnostics = []
            for key, label in [("condition_number", "condition number"), ("max_leverage", "max leverage"), ("max_cooks_distance", "max Cook's distance")]:
                if pd.notna(r.get(key)):
                    diagnostics.append(f"{label}={fmt(r.get(key))}")
            if diagnostics:
                lines.append("  - Model diagnostics: " + "; ".join(diagnostics) + ".")
        if str(r.get("type")) == "fisher_exact" and _truthy(r.get("zero_cell_correction_applied", False)):
            lines.append(
                f"  - Sparse 2×2 table: at least one cell is zero. The exact Fisher p-value uses the uncorrected table; "
                f"the finite reported odds ratio and CI use a {fmt(r.get('zero_cell_correction'))} Haldane-Anscombe correction."
            )
        if str(r.get("type")) == "welch_anova":
            lines.append(
                f"  - Welch omnibus details: groups={int(float(r.get('n_groups')))}; F({fmt(r.get('df_num'))}, {fmt(r.get('df_denom'))})={fmt(r.get('statistic'))}; "
                f"declared levels={r.get('group_levels_json')}; rows outside declared levels={int(float(r.get('n_rows_outside_declared_groups', 0) or 0))}."
            )
        if str(r.get("type")) == "welch_contrast":
            lines.append(
                f"  - Planned contrast details: weights={r.get('contrast_terms_json')}; t({fmt(r.get('df'))})={fmt(r.get('statistic'))}; "
                f"SE={fmt(r.get('standard_error'))}; rows outside declared contrast levels={int(float(r.get('n_rows_outside_declared_groups', 0) or 0))}."
            )
        if str(r.get("type")) == "poisson_regression":
            lines.append(
                f"  - Count-model diagnostics: Pearson dispersion={fmt(r.get('pearson_dispersion_ratio'))}; "
                f"deviance/df={fmt(r.get('deviance_dispersion_ratio'))}; zero fraction={fmt(r.get('zero_fraction'))}; "
                f"offset mode=`{r.get('offset_mode')}`."
            )
        if str(r.get("type")) == "chi_square" and pd.notna(r.get("min_expected")):
            lines.append(
                f"  - Chi-square expected counts: min={fmt(r.get('min_expected'))}; <5={int(float(r.get('expected_lt5_count', 0)))} "
                f"({fmt(r.get('expected_lt5_fraction', 0))} of cells); <1={int(float(r.get('expected_lt1_count', 0)))}."
            )
        note = r.get("estimand_note")
        if isinstance(note, str) and note.strip():
            lines.append(f"  - Estimand note: {note}")
    lines += [
        "",
        "The p-values above are inferential diagnostics under their stated model/test assumptions. Effect magnitude, uncertainty, missingness, and design validity should be interpreted before threshold-based language.",
        "",
        "## 4. Multiplicity",
        "",
    ]
    if plan.get("multiplicity"):
        for fam, spec in plan.get("multiplicity", {}).items():
            ids = [a["analysis_item_id"] for a in plan.get("analyses", []) if a.get("multiplicity_family") == fam]
            lines.append(f"- `{fam}`: method `{spec.get('method', 'none')}` across {len(ids)} planned test(s). {spec.get('justification', '')}".rstrip())
    else:
        lines.append("- No multiplicity families were declared.")

    lines += ["", "## 5. Sensitivity analyses", ""]
    if len(sensitivity):
        for _, r in sensitivity.iterrows():
            relation = str(r.get("estimand_relation", "uncertain"))
            lines.append(
                f"- **{r.get('sensitivity_id')}** (base `{r.get('base_analysis_item_id')}`): "
                f"{r.get('type')} estimate = {fmt(r.get('estimate'))}, CI [{fmt(r.get('ci_low'))}, {fmt(r.get('ci_high'))}], "
                f"p = {fmt(r.get('p_value'))}; rows {int(r.get('rows_before'))} → {int(r.get('rows_after'))}; "
                f"estimand relation: `{relation}`. Rationale: {r.get('rationale')}"
            )
            if str(r.get("data_filter_json", "{}")) not in {"{}", "nan", ""}:
                lines.append(f"  - Declared filter: `{r.get('data_filter_json')}`")
            if str(r.get("analysis_overrides_json", "{}")) not in {"{}", "nan", ""}:
                lines.append(f"  - Analysis overrides: `{r.get('analysis_overrides_json')}`")
            if pd.notna(r.get("n_rows_missing_pair_id")) and int(float(r.get("n_rows_missing_pair_id"))) > 0:
                lines.append(f"  - Pair-ID validity: {int(float(r.get('n_rows_missing_pair_id')))} row(s) with missing pair IDs were excluded before pairing.")
            if relation == "same" and pd.notna(r.get("estimate_change_from_base")):
                lines.append(f"  - Estimate change from base: {fmt(r.get('estimate_change_from_base'))}.")
            else:
                lines.append("  - Numeric estimate differences are not interpreted as direct robustness magnitude unless the plan explicitly declares the same estimand.")
    else:
        lines.append("- No sensitivity result file was supplied / no sensitivity analyses were planned.")

    lines += ["", "## 6. Scope and interpretation guardrails", ""]
    lines += [
        "- A non-significant difference test is not evidence of equivalence. Equivalence claims require prespecified margins and an equivalence analysis such as TOST.",
        "- Association/regression does not by itself establish causality.",
        "- `ancova_two_group` assumes an additive linear adjustment with common covariate slopes; interactions, nonlinear effects, clustered/repeated data, or post-treatment covariates require a broader analysis strategy.",
        "- `logistic_regression` supports numeric predictors and a declared binary event orientation; categorical predictors, penalization, rare-event corrections, or separation-sensitive workflows require a broader model.",
        "- `welch_anova` is an omnibus test and does not identify which groups differ; follow-up comparisons must be separately prespecified and multiplicity-aware.",
        "- `welch_contrast` tests only the exact prespecified weighted combination of group means. Contrast weights are not normalized automatically, and data-driven contrast selection is outside the core workflow.",
        "- `poisson_regression` is not a universal count model; overdispersion, excess zeros, clustering, or mixture processes may require a broader count-model workflow.",
        "- Rank-based tests are not automatically tests of median differences; descriptive medians are labeled accordingly.",
        "- Complete-case analysis is explicit, not neutral. The amount and mechanism of missingness can still bias inference and remain a scientific limitation unless addressed by design or a justified missing-data model.",
        "- Sensitivity analyses should be reported as a set, not selectively chosen after seeing which result is preferred.",
        "- Any dependence, clustering, repeated-measure, measurement-error, or model-form limitation not resolved by the declared plan remains a limitation of inference.",
        "",
        "## 7. QA and provenance",
        "",
    ]
    if preflight:
        lines.append(f"- Preflight status: **{preflight.get('status')}**")
        if preflight.get("deterministic_result_reconciliation") is not None:
            lines.append(f"- Deterministic result reconciliation: **{preflight.get('deterministic_result_reconciliation')}**")
        if preflight.get("deterministic_sensitivity_reconciliation") is not None:
            lines.append(f"- Deterministic sensitivity reconciliation: **{preflight.get('deterministic_sensitivity_reconciliation')}**")
        lines.append(f"- Preflight warnings: {len(preflight.get('warnings', []))}; errors: {len(preflight.get('errors', []))}")
        for warning in preflight.get("warnings", []):
            lines.append(f"  - Warning: {warning}")
        for error in preflight.get("errors", []):
            lines.append(f"  - Error: {error}")
    else:
        lines.append("- Preflight report: not supplied to report builder.")
    if provenance:
        lines.append(f"- Provenance manifest skill version: `{provenance.get('skill_version')}`")
        lines.append(f"- Provenance manifest created at: `{provenance.get('created_at_utc')}`")
    else:
        lines.append("- Provenance manifest: generated after this deterministic report in the recommended workflow, so the manifest can hash the report itself.")

    lines += [
        "",
        "## 8. Researcher interpretation",
        "",
        "Complete this section with domain context, practical importance, missingness mechanism, model assumptions that require scientific judgment, and the claim strength justified by the study design.",
        "",
    ]

    out = Path(args.out); out.parent.mkdir(parents=True, exist_ok=True); out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__": main()
